### ISSUE TITLE
Running example errors

### ISSUE THREAD

**Issue by JefferyDaHu** [Pangyk/Graph_AE#2]
Hi @Pangyk, Thank you for your great work. I find I am not able to use the augment_adj function in the code. There is an error message shown in the attached figure. I tried different datasets and models. They all show this error. I use the latest PYG. It seems that it is an issue with the new version of PYG.
![image](https://user-images.githubusercontent.com/29313094/143499367-89f3157f-f7e6-44a7-ac08-954bd1d71c53.png)

**Comment by Yvonne0413** [comment]
Hi I have met the same problem, have you already solved it?

**Comment by Pangyk** [comment]
We are still working on it.

**Comment by Yvonne0413** [comment]
> We are still working on it.

Thanks for working on that! Is this a problem relating to the pyG version or it is because the torch_sparse spspmm function is upgraded? I am also trying to debugging this, and don't know what's your opinion from your side.

**Comment by Pangyk** [comment]
We traced spspmm -> tensor.SparseTensor -> storage.SparseStorage. The dimension in the first two functions seems correct. But in storage.SparseStorage, the dim suddenly becomes zero.

**Comment by Yvonne0413** [comment]
Yes, it seems to be related to torch sparse. I have tried to comment out the line: `e, _ = self.augment_adj(e, None, f.shape[0])` , and it can start training, would that influence the model validation or performance?

**Comment by Pangyk** [comment]
The code is to update edges after pooling. It might influence the performance.

**Comment by Pangyk** [comment]
The bug is fixed. Thanks!

**Comment by InfraSmartLab** [comment]
Thank you very much, @Pangyk.
